### ISSUE TITLE
Update windows compilers

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/sdl_image-feedstock#9]
Hey all

This feedstock is directly specifying `vs2017_win-64` as a dependency,
https://github.com/conda-forge/sdl_image-feedstock/blob/dff4a7d99df9238337fa7786c624c3df1c35e309/recipe/meta.yaml#L18-L22

but should just rely on the `{{ compiler('c') }}` function to provide the correct compilers on windows. In particular, conda-forge has moved on to vs2019 as the default compiler a while ago already.

If you think you need vs2017, please let us know why (generally vs2019 and vs2022 should be fully compatible). If it's really necessary, please use the dedicated mechanism in `conda_build_config.yaml` for that, i.e.
```
c_compiler:     # [win]
  - vs2017      # [win]
cxx_compiler:   # [win]
  - vs2017      # [win]
```
as opposed to specifying it in `meta.yaml` directly.

**Comment by traversaro** [comment]
I think the direct specification of vs2017 is a leftover from the past, let's see if just removing it works fine.

**Comment by h-vetinari** [comment]
Thanks for the quick response!
